import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  publicDir: 'public',
  build: {
    outDir: 'dist',
    sourcemap: 'inline', // Recommended for debugging extensions
    rollupOptions: {
      input: {
        background: 'src/background.ts',
        content: 'src/content/index.tsx',
      },
      output: {
        entryFileNames: '[name].js',
        chunkFileNames: 'assets/[name].js',
        assetFileNames: (assetInfo) => {
          // The CSS file from our content script entry should be at the root.
          if (assetInfo.name?.endsWith('.css')) {
            return 'content.css';
          }
          // Keep other assets in an assets folder if any are generated by rollup.
          return 'assets/[name]-[hash].[ext]';
        },
      },
    },
  },
});